ArtyProd/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from service.views import add_blog_comment, add_comment, homePageView

from service import views

urlpatterns = [path('admin/', admin.site.urls),
               path("", include("service.urls")),
               path('', homePageView, name='home'),
               path('blog/<int:id>', views.single_blog_view, name='single_blog'),
               path('blog/<int:blog_id>/add_blog_comment/',add_blog_comment, name='add_blog_comment'),
               path('about/', views.about_view, name='about'),
               path('pricing/', views.pricing_view, name='pricing'),
               path('blog/', views.blog_item, name='blog'),
               path('services/', views.servicesPageView, name='services'),
               path('teams/', views.teams_view, name='teams'),
               path('team/<str:id>/', views.team_view, name='team'),
               path('portfolio/<int:id>/', views.portfolio_detail,
                    name='detail_portfolio'),
               path('portfolio/<int:id>/add_comment/',
                    views.add_comment, name='add_comment'),
               path('portfolio/', views.portfolio_view, name='portfolio'),
               path('register/', views.RegistrationView.as_view(), name='register'),
               path(
                   'login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
               path(
                   'logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
               path('contact/', views.contact_view, name='contact'),
               path('request/', views.create_project,
                    name='request'),



               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = 'service'

urlpatterns = [

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

service/models.py
from django.db import models
from django.db.models.constraints import UniqueConstraint
from django.contrib.auth.models import AbstractUser, Group, Permission
#to create migration files
#python manage.py makemigrations

#to migrate migration files
#python manage.py migrate

from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _

from .managers import CustomUserManager


class User(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='user_photos', null=True, blank=True)
    phone = models.CharField(max_length=15)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = CustomUserManager()
    def get_photo(self):
        return f"{self.photo}"
    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.email

class Blog(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'is_superuser': True})
    image = models.ImageField(upload_to='blog_images', null=True, blank=True)


    def __str__(self):
        return self.title
class BlogComment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content
class Project(models.Model):
    STATUS_CHOICES = (
        ('IP', 'In Progress'),
        ('C', 'Completed'),
    )
    
    title = models.CharField(max_length=100)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    client = models.ForeignKey(User, on_delete=models.CASCADE)
    services = models.ManyToManyField('Service', through='ProjectService')
    assigned_team = models.ForeignKey('Team', on_delete=models.SET_NULL, null=True)
    status = models.CharField(max_length=2, choices=STATUS_CHOICES, default='IP')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title}"
  

class Service(models.Model):
    SERVICE_TYPES = (
        ('GC', 'Graphic charter'),
        ('3D', '3D object'),
        ('SC', 'Scripting'),
    )
    name = models.CharField(max_length=50)
    icon = models.ImageField(upload_to='service_icons', blank=True, null=True)
    service_type = models.CharField(max_length=2, choices=SERVICE_TYPES)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):      
        return f"{self.name}"
    

class ProjectService(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.project.title} - {self.service.name}"
    

class Team(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    members = models.ManyToManyField(User, through='TeamMember')
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.name}"

class TeamMember(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    member = models.ForeignKey(User, on_delete=models.CASCADE)
    is_leader = models.BooleanField(default=False)
    linkedin = models.URLField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['team'], condition=models.Q(is_leader=True),
                name='unique_team_leader'
            )
        ]

    def __str__(self):
        return f"{self.member.first_name} {self.member.last_name}"


class ProjectFile(models.Model):
    PROJECT_FILE_TYPES = (
        ('IMG', 'Image'),
        ('VID', 'Video'),
        ('PDF', 'PDF Document'),
    )
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=3, choices=PROJECT_FILE_TYPES)
    file = models.FileField(upload_to='project_files')
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.project.title} - {self.file_type}"


    class Meta:
        constraints = [
            UniqueConstraint(fields=['project', 'file_type'], name='unique_project_file')
        ]
class Testimonial(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    author_name = models.CharField(max_length=100)
    author_company = models.CharField(max_length=100)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.project.title} - {self.author_name}"

class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return f"{self.title}"
    
class Comment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.project.title} - {self.user.first_name} {self.user.last_name}"

service/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from .models import Blog, Project, ProjectFile, ProjectService, Service, Team, TeamMember, Testimonial, Article,Comment,User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.shortcuts import render, redirect
from django.views import View
from .forms import ArticleForm, CommentForm, CustomRegistrationForm, ProjectForm, blogCommentForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

@login_required(login_url='login')
def create_project(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.user = request.user
            project.status = 'in_progress'
            project.client = request.user  # Set the current user as the client
            project.save()
            return redirect('request')     # Replace 'project_list' with the appropriate URL or view name for your project list
    else:
        form = ProjectForm()
        projects = Project.objects.filter(client=request.user)  # Fetch all projects created by the logged-in user
    
    return render(request, 'create_project.html', {'form': form , 'navbar': 'request', 'projects': projects})
def about_view(request):
    projects = Project.objects.filter(status="C").count()
    
    users=User.objects.all().count()

    return render(request,'about.html',{"projects":projects, "users":users})

class RegistrationView(View):
    def get(self, request):
        form = CustomRegistrationForm()
        return render(request, 'registration.html', {'form': form})

    def post(self, request):
        form = CustomRegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login')  # Replace 'login' with the URL name of your login page
        return render(request, 'registration.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})

def homePageView(request):
    projects = Project.objects.all().count()
    users=User.objects.all().count()
    team=Team.objects.all().count()
    teamMember=TeamMember.objects.all().count()
    return render(request, 'home.html', {'projects': projects , 'navbar': 'home' , "users":users, "team":team, "teamMember":teamMember})

def servicesPageView(request):
    services = Service.objects.all()
    return render(request, 'services.html', {'services': services, 'navbar': 'services'})



def team_view(request, id):
    team = get_object_or_404(Team, id=id)
    members = team.members.all()
    completed_projects = team.project_set.filter(status='C')
    in_progress_projects = team.project_set.filter(status='IP')
    
    return render(request, 'team.html', {
        'team': team,
        'members': members,
        'completed_projects': completed_projects,
        'in_progress_projects': in_progress_projects,
        'navbar': 'teams'
    })


def teams_view(request):
    teams = Team.objects.all()
     # Create a paginator with 10 items per page
    paginator = Paginator(teams, 2)

    # Get the current page number from the request's GET parameters
    page_number = request.GET.get('page')

    # Get the Page object for the current page number
    page_obj = paginator.get_page(page_number)
    context = {
        'teams': page_obj
        ,'navbar': 'teams'
    }

    return render(request, 'teams.html', context)
def contact_view(request):
    if request.method == 'POST':
        # Handle contact form submission
        pass
    else:
        # Render contact form template
        return render(request, 'contact.html')



@login_required(login_url='login')
def add_comment(request, id):
    project = get_object_or_404(Project, id=id)

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.project = project
            comment.user = request.user
            comment.save()
            return redirect('detail_portfolio', id=id)

    return redirect('detail_portfolio', id=id)

def portfolio_detail(request, id):
    project = get_object_or_404(Project, id=id)
    comments = Comment.objects.filter(project=project)
    comment_form = CommentForm()

    # Get the ProjectService objects for the project
    project_services = ProjectService.objects.filter(project=project)

    context = {
        'project': project,
        'comments': comments,
        'comment_form': comment_form,
        'project_services': project_services,
        'navbar': 'portfolio',
    }
    return render(request, 'detail_portfolio.html', context)

from django.shortcuts import render
from django.core.paginator import Paginator
from django.db.models import Q

def portfolio_view(request):
    projects = Project.objects.filter(status='C')
    Projects_S = ProjectService.objects.all()
    Projectf = ProjectFile.objects.all()

    # Create a paginator with 10 items per page
    paginator = Paginator(projects, 6)

    # Get the current page number from the request's GET parameters
    page_number = request.GET.get('page')

    # Get the Page object for the current page number
    page_obj = paginator.get_page(page_number)


    return render(request, 'portfolio.html', {
        'projects': page_obj,
        'projects_S': Projects_S,
        'projectf': Projectf,
        'navbar': 'portfolio'
    })
@login_required(login_url='login')
def contact_view(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            return redirect('contact')  # Replace 'article_list' with the name of your article list view
    else:
        form = ArticleForm()
    return render(request, 'contact.html', {'form': form})

#partie static

def blog_item(request):
    blogs = Blog.objects.all()

    context = {
        'blogs': blogs,
    }

    return render(request, 'blog.html', context)

def pricing_view(request):
    return render(request,'pricing.html')



def single_blog_view(request, id):
    blog = get_object_or_404(Blog, id=id)
    comments = blog.comments.all()
    blogform = blogCommentForm()
    context = {
        'blog': blog,
        'comments': comments,
        'form': blogform,
    }
    return render(request, 'blog_single.html', context)
@login_required(login_url='login')
def add_blog_comment(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    
    if request.method == 'POST':
        form = blogCommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = blog
            comment.user = request.user
            comment.save()
            return redirect('single_blog', id=blog_id)
    return redirect('single_blog', id=blog_id)

templates/blog_single.html
{% extends 'base.html' %}



{% block content %}

{% load static %}
<!DOCTYPE html>



<html lang="zxx">
<head>

  <!-- ** Basic Page Needs ** -->
  <meta charset="utf-8">
  <title>blog single </title>

  <!-- ** Mobile Specific Metas ** -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Agency HTML Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name="author" content="Themefisher">
  <meta name="generator" content="Themefisher Html5 Agency Template v1.0">

  

</head>

<body>


<section class="page-title bg-1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="block text-center">
          <span class="text-white">News details</span>
          <h1 class="text-capitalize mb-4 text-lg">Blog Single</h1>
          <ul class="list-inline">
            <li class="list-inline-item"><a href="{% url 'home' %}" class="text-white">Home</a></li>
            <li class="list-inline-item"><span class="text-white">/</span></li>
            <li class="list-inline-item text-white-50">News details</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section blog-wrap bg-gray">
	<div class="container">
		<div class="row">
			<div class="col-lg-20">
				<div class="row">
					<div class="col-lg-12 mb-5">
						<div class="single-blog-item">
							<img loading="lazy" src="{{ blog.image.url }}" alt="blog" class="img-fluid rounded">

							<div class="blog-item-content bg-white p-5">
								<div class="blog-item-meta bg-gray pt-2 pb-1 px-3">
									<span class="text-muted text-capitalize d-inline-block mr-3"><i class="ti-pencil-alt mr-2"></i>{{ blog.author }}</span>
								<span class="text-black text-capitalize d-inline-block mr-3"><i class="ti-time mr-1"></i>{{ blog.created_at }}</span>
								</div>

								<h2 class="mt-3 mb-4">{{blog.title}}</h2>

								<h3 class="quote">{{blog.content}}</h3>

							</div>
						</div>
					</div>

					<div class="col-lg-12 mb-5">
						<div class="comment-area card border-0 p-5">
							<h4 class="mb-4">{{ comments.count }} Comments</h4>
							{% if comments %}

							<ul class="comment-tree list-unstyled">
								{% for comment in comments %}

								<li class="mb-5">
									<div class="comment-area-box">
										<h5 class="mb-1">{{ comment.user }}</h5>
										<div class="comment-meta mt-4 mt-lg-0 mt-md-0 float-lg-right float-md-right">
											<span class="date-comm">{{ comment.created_at }}</span>
										</div>

										<div class="comment-content mt-3">
											<p>{{ comment.content }}</p>
										</div>
									</div>
								</li>
								{% endfor %}

								
							</ul>
							{% else %}
							<p>No comments yet.</p>
							{% endif %}					

						</div>
					</div>
					<h3>Add a Comment</h3>

					<div class="col-lg-12">
						<form class="contact-form bg-white rounded p-5" id="comment-form" method="POST" action="{% url 'add_blog_comment' blog.id %}">
							{% csrf_token %}
							{{ form.content.errors }}
							<textarea class="form-control mb-3" name="content" id="comment" cols="30" rows="5" placeholder="Comment"></textarea>
					
							<button class="btn btn-main btn-round-full" type="submit">Submit Comment</button>
						</form>
					</div>
				</div>
			</div>

			
		</div>
	</div>
</section>


<!--Scroll to top-->
<div id="scroll-to-top" class="scroll-to-top">
  <span class="icon fa fa-angle-up"></span>
</div>



</body>

</html>

{% endblock %}

templates/detail_portfolio.html
    {% extends 'base.html' %}

    {% block content %}
        <section class="page-title bg-1">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="block text-center">
                            <span class="text-white">Latest works</span>
                            <h1 class="text-capitalize mb-4 text-lg">Portfolio Detail</h1>
                            <ul class="list-inline">
                                <li class="list-inline-item"><a href="index.html" class="text-white">Home</a></li>
                                <li class="list-inline-item"><span class="text-white">/</span></li>
                                <li class="list-inline-item"><a href="{% url 'portfolio' %}" class="text-white">Portfolio</a></li>
                                <li class="list-inline-item"><span class="text-white">/</span></li>
                                <li class="list-inline-item text-white-50">{{ project.title }}</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        
        <section class="section portfolio-detail">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="portfolio-detail-image">
                            {% for pf in project.projectfile_set.all %}
                                {% if pf.file_type == 'IMG' %}
                                    <img src="{{ pf.file.url }}" alt="{{ project.title }} Image" class="img-fluid">
                                {% endif %}
                            {% empty %}
                                <!-- If there is no image file, you can display a placeholder image -->
                                <img src="fdsgfd_6w7Lpkr.jpg" alt="Placeholder Image" class="img-fluid">
                            {% endfor %}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="portfolio-detail-content">
                            <h2>{{ project.title }}</h2>
                            <p>{{ project.description }}</p>
                            <h5>Project Details</h5>
                            <li><strong>Client :</strong> {{ project.client }}</li>
                            <li><strong>services :</strong> 
                                  <ul>
                            {% for project_service in project_services %}
                            <li>{{ project_service.service.name }}</li>
                            {% endfor %}
                        </ul>

                            </li>

                            
                            
                            
                            {% for pf in project.projectfile_set.all %}
                                {% if pf.file_type == 'VID' %}
                                    <div class="embed-responsive embed-responsive-16by9">
                                        <video controls>
                                            <source src="{{ pf.file.url }}" type="video/mp4">
                                        </video>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            {% for pf in project.projectfile_set.all %}
                                {% if pf.file_type == 'PDF' %}
                                    <a href="{{ pf.file.url }}" class="btn btn-main btn-small" style="margin-top: 30px;">Download PDF</a>
                                {% endif %}
                            {% endfor %}
                            <ul>
                                {% for project_S in projects_S %}
                                    {% if project_S.project.id == project.id %}
                                        <li>{{ project_S.service.name }}</li>
                                    {% endif %}
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <div class="comment-area card border-0 p-5">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 mb-5">
                        <div class="comment-area card border-0 p-5">
                            <h4 class="mb-4">{{ project.comments.count }} Comments</h4>
                            <ul class="comment-tree list-unstyled">
                                {% for comment in project.comments.all %}
                                <li class="mb-5">
                                    <div class="comment-area-box">
        
                                        <span>{{ comment.user.email }}</span>
        
                                        <div class="comment-meta mt-4 mt-lg-0 mt-md-0 float-lg-right float-md-right">
                                            <span class="date-comm">Posted {{ comment.created_at|date:"F d, Y" }}</span>
                                        </div>
        
                                        <div class="comment-content mt-3">
                                            <p>{{ comment.text }}</p>
                                        </div>
                                    </div>
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        

    {% if request.user.is_authenticated %}
    <section class="section comment-form-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <form class="contact-form bg-white rounded p-5" method="POST" action="{% url 'add_comment' id=project.id %}">
                        {% csrf_token %}
                        <h4 class="mb-4">Write a comment</h4>
                        {{ comment_form.content.errors }}
                        {{ comment_form.text }}
                        <input class="btn btn-main btn-round-full" type="submit" value="Submit Comment" id="submit_contact">
                    </form>
                </div>
            </div>
        </div>
    </section>
    {% else %}
    <section class="section comment-form-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <p>Please log in to leave a comment.</p>
                </div>
            </div>
        </div>
    </section>
    {% endif %}

    {% endblock %}

templates/team.html
{% extends "base.html" %}
{% block content %}


<section class="section about-2 position-relative" style="padding-bottom: 0px;">
	<div class="container">
		<div class="row">
			<div class="col-lg-7">
				<div class="about-item pr-3 mb-5 mb-lg-0">
					<span class="h6 text-color">What we are </span><span class="h6 ">{{ team.name }}</span>
					<h2 class="mt-3 mb-4 position-relative content-title">We are dynamic team of creative people</h2>
					<p class="mb-5">{{ team.description }}</p>
				</div>
			</div>
		</div>
	</div>
</section>
<!--  Section Services Start -->
<section class="section team">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-7 text-center">
				<div class="section-title">
					<span class="h6 text-color">Our Team</span>
					<h2 class="mt-3 content-title">Expert Team member to get best service</h2>
				</div>
			</div>
		</div>
		
		<div class="row justify-content-center">
			{% for member in team.members.all %}
				<div class="col-lg-4 col-md-6 col-sm-6">
					<div class="team-item-wrap mb-5">
						<div class="team-item position-relative">
							
						<img loading="lazy" src="{{ member.photo.url }}" alt="team" class="img-fluid w-100 img">
						<div class="team-img-hover">
							<ul class="team-social list-inline">
							
							<li class="list-inline-item">
								<a href="{{ member.teammember_set.first.linkedin }}" class="linkedin"><i class="fab fa-linkedin-in" aria-hidden="true"></i></a>

							</li>
							</ul>
						</div>
						</div>
						<div class="team-item-content">
						<h4 class="mt-3 mb-0 text-capitalize">{{ member.first_name }} {{ member.last_name }}</h4>
						
						
						{% for team_member in member.teammember_set.all %}
						{% if team_member.is_leader %}
							<p>Team Leader</p>
						{% else %}
							<p>Team Member</p>
						{% endif %}
					{% endfor %}

						</div>
					</div>
				</div>
			{% endfor %}

		</div>
	</div>
</section>
<section>
	<table>
		<thead>
		  <tr>
			<th>Completed Projects</th>
			<th>In-Progress Projects</th>
		  </tr>
		</thead>
		<tbody>
		  <tr>
			<td>
			  {% for project in completed_projects %}
				<p>{{ project.title }}</p>
			  {% empty %}
				<p>No completed projects</p>
			  {% endfor %}
			</td>
			<td>
			  {% for project in in_progress_projects %}
				<p>{{ project.title }}</p>
			  {% empty %}
				<p>No in-progress projects</p>
			  {% endfor %}
			</td>
		  </tr>
		</tbody>
	  </table>
</section>

<!--  Section Services End -->
<!-- Section Testimonial Start -->
<section class="section testimonial bg-gray">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-7 text-center">
				<div class="section-title">
					<span class="h6 text-color">Clients testimonial</span>
					<h2 class="mt-3 content-title">Check what's our clients say about us</h2>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="testimonial-wrap">
			<div class="testimonial-item position-relative">
				<i class="ti-quote-left text-color"></i>

				<div class="testimonial-item-content">
					<p class="testimonial-text">Quam maiores perspiciatis temporibus odio reiciendis error alias debitis atque consequuntur natus iusto recusandae numquam corrupti facilis blanditiis.</p>

					<div class="testimonial-author">
						<h5 class="mb-0 text-capitalize">Thomas Johnson</h5>
						<p>Excutive Director,themefisher</p>
					</div>
				</div>
			</div>
			<div class="testimonial-item position-relative">
				<i class="ti-quote-left text-color"></i>

				<div class="testimonial-item-content">
					<p class="testimonial-text">Consectetur adipisicing elit. Quam maiores perspiciatis temporibus odio reiciendis error alias debitis atque consequuntur natus iusto recusandae .</p>

					<div class="testimonial-author">
						<h5 class="mb-0 text-capitalize">Mickel hussy</h5>
						<p>Excutive Director,themefisher</p>
					</div>
				</div>
			</div>
			<div class="testimonial-item position-relative">
				<i class="ti-quote-left text-color"></i>

				<div class="testimonial-item-content">
					<p class="testimonial-text">Quam maiores perspiciatis temporibus odio reiciendis error alias debitis atque consequuntur natus iusto recusandae numquam corrupti.</p>

					<div class="testimonial-author">
						<h5 class="mb-0 text-capitalize">James Watson</h5>
						<p>Excutive Director,themefisher</p>
					</div>
				</div>
			</div>
			<div class="testimonial-item position-relative">
				<i class="ti-quote-left text-color"></i>

				<div class="testimonial-item-content">
					<p class="testimonial-text">Consectetur adipisicing elit. Quam maiores perspiciatis temporibus odio reiciendis error alias debitis atque consequuntur natus iusto recusandae .</p>

					<div class="testimonial-author">
						<h5 class="mb-0 text-capitalize">Mickel hussy</h5>
						<p>Excutive Director,themefisher</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

  <style>
	table {
	  width: 100%;
	  border-collapse: collapse;
	  margin-bottom: 20px;
	}
	table p  {

		text-align: center;
	}
	th, td {
	  padding: 10px;
	  text-align: left;
	  border-bottom: 1px solid #ddd;
	  text-align: center;
	}
  
	th {
	  background-color: #f2f2f2;
	  font-weight: bold;
	}
  
	tr:hover {
	  background-color: #f5f5f5;
	}
  </style>
	
<style>
	.img {
		width: 330px; /* Set the desired width */
		height:	450px; /* Set a fixed height */
		object-fit: cover; /* Maintain the aspect ratio and crop if necessary */
	}
</style>

{% endblock %}